name: Build and Deploy JAR

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn clean install

    - name: Commit and push the JAR file to GitHub
      run: |
        git config  user.name "GitHub Actions"
        git config  user.email "actions@github.com"
        git add target
        git commit -m "Add generated JAR"
        git push https://${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git HEAD:main
        fi
