name: Generate Javadoc

on: [push]

jobs:
  generate-javadoc:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    - name: Generate Javadoc
      run: mvn javadoc:javadoc --batch-mode
    - name: Commit and Push Javadoc
      run: |
        git config user.name "GitHub Actions"
        git config user.email "actions@github.com"
        git add target/site/apidocs
        if git diff --cached --quiet; then
          echo "No changes in Javadoc to commit."
        else
          git commit -m "Update Javadoc"
          git push origin main
        fi
